export enum DoorVariant {
  DOOR_UNSPECIFIED = 0,
  DOOR_LOCKED,
  DOOR_LOCKED_DOUBLE,
  DOOR_LOCKED_CRACKED,
  DOOR_LOCKED_BARRED,
  DOOR_LOCKED_KEYFAMILIAR,
  DOOR_LOCKED_GREED,
  DOOR_HIDDEN,
  DOOR_UNLOCKED
}