export enum ProjectileVariant {
  PROJECTILE_NORMAL = 0,
  PROJECTILE_BONE = 1,
  PROJECTILE_FIRE = 2,
  PROJECTILE_PUKE = 3,
  PROJECTILE_TEAR = 4,
  PROJECTILE_CORN = 5,
  PROJECTILE_HUSH = 6,
  PROJECTILE_COIN = 7,
  PROJECTILE_GRID = 8,
  PROJECTILE_ROCK = 9,
  PROJECTILE_RING = 10,
  PROJECTILE_MEAT = 11,
  PROJECTILE_FCUK = 12,
  PROJECTILE_WING = 13,
  PROJECTILE_LAVA = 14,
  PROJECTILE_HEAD = 15,
  PROJECTILE_PEEP = 16
}